class Commands:
    TAKEOFF = 'TAKEOFF'
    LAND = 'LAND'
    FORWARD = 'FORWARD'
    BACKWARDS = 'BACKWARDS'
    LEFT = 'LEFT'
    RIGHT = 'RIGHT'
    UP = 'UP'
    DOWN = 'DOWN'
    R_CW = 'R_CW'
    R_CCW = 'R_CCW'
