class Commands:
    TAKEOFF = 'TAKEOFF'
    LAND = 'LAND'
    STOP = 'STOP'
    FORWARD = 'FORWARD'
    BACKWARDS = 'BACKWARDS'
    LEFT = 'LEFT'
    RIGHT = 'RIGHT'
    UP = 'UP'
    DOWN = 'DOWN'
    R_CW = 'R_CW'
    R_CCW = 'R_CCW'
    F_R = 'F_R'
    F_L = 'F_L'
    F_F = 'F_F'
    F_B = 'F_B'
    STOP_VIDEO = 'STOP_VIDEO'
    START_VIDEO = 'START_VIDEO'
